name: Invitation to GDSC-TKNP GitHub Community.
description: I would like to be part of the awesome community
title: "Invite me to GDSC-TKNP GitHub Community"
labels: [Invitation to the community]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: twitter
    attributes:
      label: Twitter Username (Optional)
      placeholder: Insert your Twitter username here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: Where did you heard GDSC-TKNP? What do you like about this community/Why do you want to join?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You can also join our Twitter community [here](https://twitter.com/Gdsctknp)
        Feel free to check out other cool repositories of the GDSC-TKNP Community [here](https://github.com/GDSC-TKNP)
