on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: GDSC-TKNP
          label: invite me to the GDSC-TKNP Community
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Welcome to the Google Developer Student Club - The Kisumu National Polytechnic.'
          existingMemberMessage: You are already a member of our Organisation.
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
